# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/generic
src/reflect
src/unicode
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-unicode-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/generic/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-unicode-include.h
src/reflect/_mulle-unicode-versioncheck.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/generic/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/mulle-unicode-ctype.h
src/mulle-unicode.h
src/mulle-unicode-is-alphanumeric.h
src/mulle-unicode-is-capitalized.h
src/mulle-unicode-is-control.h
src/mulle-unicode-is-decimaldigit.h
src/mulle-unicode-is-decomposable.h
src/mulle-unicode-is-legalcharacter.h
src/mulle-unicode-is-letter.h
src/mulle-unicode-is-lowercase.h
src/mulle-unicode-is-newline.h
src/mulle-unicode-is-nonbase.h
src/mulle-unicode-is-noncharacter.h
src/mulle-unicode-is-punctuation.h
src/mulle-unicode-is-symbol.h
src/mulle-unicode-is-uppercase.h
src/mulle-unicode-is-whitespace.h
src/mulle-unicode-is-whitespaceornewline.h
src/mulle-unicode-is-zerodigit.h
src/mulle-unicode-tolower.h
src/mulle-unicode-toupper.h
src/unicode/miniplane.h
)

