#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-unicode-include-private.h
)

set( PRIVATE_HEADERS
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-unicode-include.h
)

set( PUBLIC_HEADERS
src/include.h
src/mulle-unicode-ctype.h
src/mulle-unicode.h
src/mulle-unicode-is-alphanumeric.h
src/mulle-unicode-is-capitalized.h
src/mulle-unicode-is-control.h
src/mulle-unicode-is-decimaldigit.h
src/mulle-unicode-is-decomposable.h
src/mulle-unicode-is-legalcharacter.h
src/mulle-unicode-is-letter.h
src/mulle-unicode-is-lowercase.h
src/mulle-unicode-is-newline.h
src/mulle-unicode-is-nonbase.h
src/mulle-unicode-is-noncharacter.h
src/mulle-unicode-is-privatecharacter.h
src/mulle-unicode-is-punctuation.h
src/mulle-unicode-is-symbol.h
src/mulle-unicode-is-uppercase.h
src/mulle-unicode-is-validurlfragment.h
src/mulle-unicode-is-validurlhost.h
src/mulle-unicode-is-validurlpassword.h
src/mulle-unicode-is-validurlpath.h
src/mulle-unicode-is-validurlquery.h
src/mulle-unicode-is-validurlscheme.h
src/mulle-unicode-is-validurluser.h
src/mulle-unicode-is-whitespace.h
src/mulle-unicode-is-whitespaceornewline.h
src/mulle-unicode-is-zerodigit.h
src/mulle-unicode-tolower.h
src/mulle-unicode-toupper.h
src/unicode/isalphanumeric-utf16-inv.inc
src/unicode/isalphanumeric-utf32-inv.inc
src/unicode/iscapitalized-utf16.inc
src/unicode/iscontrol-utf16.inc
src/unicode/iscontrol-utf32.inc
src/unicode/isdecimaldigit-utf16.inc
src/unicode/isdecimaldigit-utf32.inc
src/unicode/isdecomposable-utf16.inc
src/unicode/isdecomposable-utf32.inc
src/unicode/isdigit-utf16.inc
src/unicode/isdigit-utf32.inc
src/unicode/islegal-utf16.inc
src/unicode/islegal-utf32.inc
src/unicode/isletter-utf16-inv.inc
src/unicode/isletter-utf32-inv.inc
src/unicode/islowercase-utf16.inc
src/unicode/islowercase-utf32.inc
src/unicode/isnonbase-utf16.inc
src/unicode/isnonbase-utf32.inc
src/unicode/isnumeric-utf16.inc
src/unicode/isnumeric-utf32.inc
src/unicode/isprivate-utf16.inc
src/unicode/isprivate-utf32.inc
src/unicode/ispunctuation-utf16.inc
src/unicode/ispunctuation-utf32.inc
src/unicode/isseparator-utf16.inc
src/unicode/issymbol-utf16.inc
src/unicode/issymbol-utf32.inc
src/unicode/isuppercase-utf16.inc
src/unicode/isuppercase-utf32.inc
src/unicode/iswhitespace-utf16.inc
src/unicode/iszerodigit-utf16.inc
src/unicode/iszerodigit-utf32.inc
src/unicode/tolower-utf16.inc
src/unicode/tolower-utf32.inc
src/unicode/totitlecase-utf16.inc
src/unicode/totitlecase-utf32.inc
src/unicode/toupper-utf16.inc
src/unicode/toupper-utf32.inc
)

