#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/mulle-unicode-is-alphanumeric.c
src/mulle-unicode-is-capitalized.c
src/mulle-unicode-is-control.c
src/mulle-unicode-is-decimaldigit.c
src/mulle-unicode-is-decomposable.c
src/mulle-unicode-is-legalcharacter.c
src/mulle-unicode-is-letter.c
src/mulle-unicode-is-lowercase.c
src/mulle-unicode-is-newline.c
src/mulle-unicode-is-nonbase.c
src/mulle-unicode-is-noncharacter.c
src/mulle-unicode-is-punctuation.c
src/mulle-unicode-is-symbol.c
src/mulle-unicode-is-uppercase.c
src/mulle-unicode-is-whitespace.c
src/mulle-unicode-is-whitespaceornewline.c
src/mulle-unicode-is-zerodigit.c
src/mulle-unicode-tolower.c
src/mulle-unicode-toupper.c
)

#
# contents selected with patternfile ??-source--standalone-sources
#
set( STANDALONE_SOURCES
src/mulle-unicode-standalone.c
)
