/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#include "mulle-unicode-ctype.h"
#include "mulle-unicode-is-alphanumeric.h"
#include "mulle-unicode-is-capitalized.h"
#include "mulle-unicode-is-control.h"
#include "mulle-unicode-is-decimaldigit.h"
#include "mulle-unicode-is-decomposable.h"
#include "mulle-unicode-is-legalcharacter.h"
#include "mulle-unicode-is-letter.h"
#include "mulle-unicode-is-lowercase.h"
#include "mulle-unicode-is-newline.h"
#include "mulle-unicode-is-nonbase.h"
#include "mulle-unicode-is-noncharacter.h"
#include "mulle-unicode-is-punctuation.h"
#include "mulle-unicode-is-symbol.h"
#include "mulle-unicode-is-uppercase.h"
#include "mulle-unicode-is-whitespace.h"
#include "mulle-unicode-is-whitespaceornewline.h"
#include "mulle-unicode-is-zerodigit.h"
#include "mulle-unicode-tolower.h"
#include "mulle-unicode-toupper.h"
