#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/include-private.h
)

set( PUBLIC_HEADERS
src/include.h
src/mulle-char5.h
src/mulle-char7.h
src/mulle-utf16.h
src/mulle-utf16-string.h
src/mulle-utf32.h
src/mulle-utf32-string.h
src/mulle-utf8.h
src/mulle-utf-convenience.h
src/mulle-utf-ctype.h
src/mulle-utf.h
src/mulle-utf-is-alphanumeric.h
src/mulle-utf-is-capitalized.h
src/mulle-utf-is-control.h
src/mulle-utf-is-decimaldigit.h
src/mulle-utf-is-decomposable.h
src/mulle-utf-is-legalcharacter.h
src/mulle-utf-is-letter.h
src/mulle-utf-is-lowercase.h
src/mulle-utf-is-newline.h
src/mulle-utf-is-nonbase.h
src/mulle-utf-is-noncharacter.h
src/mulle-utf-is-nonpercentescape.h
src/mulle-utf-is-privatecharacter.h
src/mulle-utf-is-punctuation.h
src/mulle-utf-is-symbol.h
src/mulle-utf-is-uppercase.h
src/mulle-utf-is-validurlfragment.h
src/mulle-utf-is-validurlhost.h
src/mulle-utf-is-validurlpassword.h
src/mulle-utf-is-validurlpath.h
src/mulle-utf-is-validurlquery.h
src/mulle-utf-is-validurlscheme.h
src/mulle-utf-is-validurluser.h
src/mulle-utf-is-whitespace.h
src/mulle-utf-is-whitespaceornewline.h
src/mulle-utf-rover.h
src/mulle-utf-scan.h
src/mulle-utf-tolower.h
src/mulle-utf-toupper.h
src/mulle-utf-type.h
src/unicode/isalphanumeric-utf16-inv.inc
src/unicode/isalphanumeric-utf32-inv.inc
src/unicode/iscapitalized-utf16.inc
src/unicode/iscontrol-utf16.inc
src/unicode/iscontrol-utf32.inc
src/unicode/isdecimaldigit-utf16.inc
src/unicode/isdecimaldigit-utf32.inc
src/unicode/isdecomposable-utf16.inc
src/unicode/isdecomposable-utf32.inc
src/unicode/isdigit-utf16.inc
src/unicode/isdigit-utf32.inc
src/unicode/islegal-utf16.inc
src/unicode/islegal-utf32.inc
src/unicode/isletter-utf16-inv.inc
src/unicode/isletter-utf32-inv.inc
src/unicode/islowercase-utf16.inc
src/unicode/islowercase-utf32.inc
src/unicode/isnonbase-utf16.inc
src/unicode/isnonbase-utf32.inc
src/unicode/isnumeric-utf16.inc
src/unicode/isnumeric-utf32.inc
src/unicode/isprivate-utf16.inc
src/unicode/isprivate-utf32.inc
src/unicode/ispunctuation-utf16.inc
src/unicode/ispunctuation-utf32.inc
src/unicode/isseparator-utf16.inc
src/unicode/issymbol-utf16.inc
src/unicode/issymbol-utf32.inc
src/unicode/isuppercase-utf16.inc
src/unicode/isuppercase-utf32.inc
src/unicode/iswhitespace-utf16.inc
src/unicode/tolower-utf16.inc
src/unicode/tolower-utf32.inc
src/unicode/totitlecase-utf16.inc
src/unicode/totitlecase-utf32.inc
src/unicode/toupper-utf16.inc
src/unicode/toupper-utf32.inc
)

